"""Analysis Critic Agent

This agent reviews and provides feedback on the analysis generated by the analysis_generator_agent.
"""

from google.adk.agents.llm_agent import LlmAgent

from ....shared_libraries import constants
from . import prompt

analysis_critic_agent = LlmAgent(
    model=constants.MODEL,
    name="analysis_critic_agent",
    description="Reviews and critiques the analysis for accuracy and helpfulness.",
    instruction=prompt.ANALYSIS_CRITIC_PROMPT,
    output_key="analysis_feedback",
)
